version: 'Build #{build}'
image: Visual Studio 2019
configuration: Release
after_test:
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
  - path: '**\*.vsix'
skip_commits:
  files:
    - '**/*.md'
    - '**/*.yml'
skip_tags: true
